#!/usr/bin/env python3
import os, sys, subprocess, fcntl

DECRYPT_CMD = (
    'gpg -d ~/.password-store/.coffin/coffin.tar.gpg'
    ' | tar -xO ./baleti-git-ssh-signing-key.gpg'
    ' | gpg -d'
)

args = list(sys.argv[1:])

if '-Y' in args and args[args.index('-Y') + 1] == 'sign':
    key = subprocess.check_output(DECRYPT_CMD, shell=True)
    key = key.replace(b'\r\n', b'\n')  # strip CRLF if present

    fd = os.memfd_create('git-signing-key')
    os.write(fd, key)
    os.fchmod(fd, 0o600)

    flags = fcntl.fcntl(fd, fcntl.F_GETFD)
    fcntl.fcntl(fd, fcntl.F_SETFD, flags & ~fcntl.FD_CLOEXEC)

    os.dup2(fd, 200)
    os.close(fd)

    for i, a in enumerate(args):
        if a == '-f' and i + 1 < len(args):
            args[i + 1] = '/proc/self/fd/200'
            break

os.execvp('ssh-keygen', ['ssh-keygen', *args])
